spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/food_tour?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: 8080

app:
  jwt:
    secret: 9a571f302a63273e93a89eeca2f808799a571f302a63273e93a89eeca2f80879
    expiration-ms: 86400000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:djdrbgix5}
  api-key: ${CLOUDINARY_API_KEY:467375341443691}
  api-secret: ${CLOUDINARY_API_SECRET:0JWvXef1_6b80tQxVPTAVovXJFM}

momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  ipn-url: https://shakily-custodian-monorail.ngrok-free.dev/api/payments/momo/callback
  redirect-url: https://shakily-custodian-monorail.ngrok-free.dev/payment/result
